# docker-compose.yaml
services:
    # nginx
    web:
        image: nginx:latest
        container_name: www_docker_nginx
        ports:
            - "8256:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/app
    # mysql
    # redis